name: CD

on:
  push:
    branches:
      - "feature/*"
      - "develop"
    paths:
      - "sources/backend/**"

permissions:
  contents: read
  id-token: write

env:
  ECS_CLUSTER: codeland-cluster
  ECS_SERVICE: codeland-service
  ECS_TASK_DEFINITION: codeland-task-definition
  CONTAINER_NAME: codeland

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod

    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }} # ap-southeast-1

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        id: build-image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker build -t ${{ vars.ECR_REGISTRY }}:$IMAGE_TAG ./sources/backend

          docker tag ${{ vars.ECR_REGISTRY }}:$IMAGE_TAG \
            ${{ vars.ECR_REGISTRY }}:latest

          docker push ${{ vars.ECR_REGISTRY }}:$IMAGE_TAG
          docker push ${{ vars.ECR_REGISTRY }}:latest

          echo "image=${{ vars.ECR_REGISTRY }}:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > ${{ env.ECS_TASK_DEFINITION }}.json

      - name: Fill in the new image name in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.build.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
