name: CI

on:
  push:
    branches:
      - "feature/*"
      - "develop"
    paths:
      - "sources/backend/**"
  pull_request:
    branches:
      - "develop"
    paths:
      - "sources/backend/**"

jobs:
  scan:
    uses: ./.github/workflows/sub_scan.yml
    with:
      working_directory: ./sources/backend
