name: ECS Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "sources/backend/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO: codeland-backend
  ECR_REGISTRY: codeland-backend-registry
  ECS_CLUSTER: codeland-cluster
  ECS_SERVICE: backend-service
  TASK_FAMILY: backend-task

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }} # ap-southeast-1

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          mask-password: "true"

      - name: Build & Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REPO:$IMAGE_TAG ./sources/backend

          docker tag $ECR_REPO:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$IMAGE_TAG
          docker tag $ECR_REPO:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:latest

          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:latest

      - name: Render Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infra/task-definitions/backend.json
          container-name: backend
          image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:${{ github.sha }}

      - name: Deploy ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: $ECS_SERVICE
          cluster: $ECS_CLUSTER
          wait-for-service-stability: true
