# name: ECS Scan Backend

# on:
#   pull_request:
#     paths:
#       - "sources/backend/**"
#   push:
#     paths:
#       - "sources/backend/**"

# jobs:
#   scan:
#     uses: ./.github/workflows/sub_scan.yml
#     with:
#       working_directory: ./sources/backend
