# name: Terraform Destroy

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Environment to destroy"
#         required: true
#         default: "prod"
#       confirm_destroy:
#         description: "Type DESTROY to confirm"
#         required: true

# permissions:
#   id-token: write
#   contents: read

# env:
#   AWS_REGION: ap-southeast-1

# jobs:
#   destroy:
#     runs-on: ubuntu-latest
#     environment: ${{ github.event.inputs.environment }}

#     steps:
#       - uses: actions/checkout@v4

#       - name: Confirm destroy
#         run: |
#           if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
#             echo "Confirmation failed"
#             exit 1
#           fi

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.GITHUB_ACTIONS_ROLE_ARN }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Terraform Init
#         run: |
#           cd infra/envs/${{ github.event.inputs.environment }}
#           terraform init

#       - name: Terraform Destroy
#         run: |
#           cd infra/envs/${{ github.event.inputs.environment }}
#           terraform destroy -auto-approve
