name: Terraform Apply

on:
  pull_request:
    paths:
      - "infra/**"
  push:
    branches: ["main"]
    paths:
      - "infra/**"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/envs/${{ vars.WORKSPACE }}

      - name: Terraform workspace
        run: |
          terraform workspace new ${{ vars.WORKSPACE }}
          terraform workspace select ${{ vars.WORKSPACE }}
        working-directory: infra/envs/${{ vars.WORKSPACE }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/envs/${{ vars.WORKSPACE }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/envs/${{ vars.WORKSPACE }}

      - name: Terraform Plan
        run: terraform plan -out=plan.out
        env:
          TF_VAR_container_image: ${{ vars.CONTAINER_IMAGE_BASE }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        working-directory: infra/envs/${{ vars.WORKSPACE }}

      # # Scan Public S3, RDS public access, SG open 0.0.0.0/0, No encryption
      # - name: Trivy IaC scan
      #   uses: aquasecurity/trivy-action@0.20.0
      #   with:
      #     scan-type: config
      #     scan-ref: terraform
      #     severity: HIGH,CRITICAL

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: terraform apply plan.out
      #   working-directory: infra/envs/${{ vars.WORKSPACE }}
